database:
  type: "sqlite"  # 支持postgresql或sqlite
  postgresql:
    host: "localhost"
    port: 5432
    database: "gitbase"
    user: "gituser"
    password: "giko"
  sqlite:
    database: "/Users/yougikou/Documents/Github/git2base/gitbase.db"  # SQLite数据库文件路径

stacks:
  # - name: Assets
  #   paths: ["assets"]
  #   extensions: []
  # - name: Application
  #   paths: ["crates"]
  #   extensions: [".rs", ".toml"]
  # - name: Extension
  #   paths: ["extensions"]
  #   extensions: [".rs", ".toml"]
  # - name: TestData
  #   paths: []
  #   extensions: [".json"]
  # - name: Script
  #   paths: ["script"]
  #   extensions: []
  # - name: Tooling
  #   paths: ["tooling"]
  #   extensions: [".rs", ".toml"]
  - name: Java
    paths: []
    extensions: ["java"]
  - name: Script
    paths: []
    extensions: ["sh", "bat"]
  - name: Github
    paths: [.github]
    extensions: []
  - name: VueScript
    paths: [frontend/src]
    extensions: ["vue"]
  - name: TypeScript
    paths: [common/src, daemon/src, frontend/src, panel/src]
    extensions: ["ts"]
  - name: CSS
    paths: [common/src, daemon/src, frontend/src, panel/src]
    extensions: ["css", "scss"]
  - name: XML
    paths: []
    extensions: ["xml"]

analyzers:
  - name: FileLineCount
    class: "FileLineCountAnalyzer"
    tech_stacks: ["All"]
  - name: FileCharCount
    class: "FileCharCountAnalyzer"
    tech_stacks: ["All"]
  - name: XMLElementCount
    class: "XMLElementCountAnalyzer"
    tech_stacks: ["XML"]
  - name: JavaClassCount
    class: "RegexMatchCountAnalyzer"
    params:
      patterns: ['(?<!\w)\bclass\s+(\w+)\b(?:\s+extends\s+(\w+))?(?:\s+implements\s+([\w\s,]+))?\s*\{']
    tech_stacks: ["Java"]
