input:
  include: [""]
  exclude: [".vscode", "data", "doc"]

output:
  type: "csv"  # 支持postgresql或sqlite或者csv
  csv:
    path: "data"  # 默认为项目的data相对路径
  postgresql:
    host: "localhost"
    port: 5432
    database: "gitbase"
    user: "gituser"
    password: "giko"
  sqlite:
    database: "gitbase.db"  # SQLite数据库文件路径 - 默认为项目的根路径

stacks:
  # - name: Assets
  #   paths: ["assets"]
  #   extensions: []
  # - name: Application
  #   paths: ["crates"]
  #   extensions: [".rs", ".toml"]
  # - name: Extension
  #   paths: ["extensions"]
  #   extensions: [".rs", ".toml"]
  # - name: TestData
  #   paths: []
  #   extensions: [".json"]
  # - name: Script
  #   paths: ["script"]
  #   extensions: []
  # - name: Tooling
  #   paths: ["tooling"]
  #   extensions: [".rs", ".toml"]
  - name: Java
    paths: []
    extensions: ["java"]
  - name: XML
    paths: []
    extensions: ["xml"]
  - name: Script
    paths: []
    extensions: ["sh", "bat"]
  - name: Python
    paths: ["config", "database", "git", "notebooks"]
    extensions: ["py"]
  - name: PyTest
    paths: ["tests"]
    extensions: ["py"]
  - name: Yaml
    paths: []
    extensions: ["yaml"]
  - name: Jupyter
    paths: [notebooks]
    extensions: ["ipynb"]

analyzers:
  - name: FileLineCount
    class: "FileLineCountAnalyzer"
    tech_stacks: ["All"]
  - name: FileCharCount
    class: "FileCharCountAnalyzer"
    tech_stacks: ["All"]
  - name: XMLElementCount
    class: "XMLElementCountAnalyzer"
    tech_stacks: ["XML"]
  - name: JavaClassCount
    class: "RegexMatchCountAnalyzer"
    params:
      patterns: ['(?<!\w)\bclass\s+(\w+)\b(?:\s+extends\s+(\w+))?(?:\s+implements\s+([\w\s,]+))?\s*\{']
    tech_stacks: ["Java"]
