name: Build Executables

on:
  workflow_dispatch: 
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable with PyInstaller
        run: pyinstaller main.py --onefile --name git2base
        shell: bash

      - name: Zip output with version
        run: |
          VERSION=${{ github.ref_name }}
          if [ -z "$VERSION" ]; then
            VERSION="manual-$(date +'%Y%m%d-%H%M%S')"
          fi
          cd dist
          zip git2base-${VERSION}-${{ matrix.os }}.zip git2base*
        shell: bash

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}