name: Build with Nuitka

on:
  workflow_dispatch: 
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Show current path
        run: pwd

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install nuitka
        shell: bash

      - name: Build with Nuitka
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            python -m nuitka --assume-yes-for-downloads --standalone --onefile --output-dir=dist --output-filename=git2base --include-package=pygit2 --include-module=_cffi_backend --follow-imports main.py
          else
            python -m nuitka --standalone --onefile --output-dir=dist --output-filename=git2base --include-package=pygit2 --include-module=_cffi_backend --follow-imports main.py
          fi
        shell: bash

      - name: Zip output with version (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          VERSION=${{ github.ref_name }}
          if [ -z "$VERSION" ]; then
            VERSION="manual-$(date +'%Y%m%d-%H%M%S')"
          fi
          cd dist
          zip git2base-${VERSION}-${{ matrix.os }}.zip git2base*

      - name: Zip output with version (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $VERSION = "${{ github.ref_name }}"
          if (-not $VERSION) {
            $VERSION = "manual-" + (Get-Date -Format "yyyyMMdd-HHmmss")
          }
          $zipName = "git2base-$VERSION-windows-latest.zip"
          Compress-Archive -Path dist\git2base.exe -DestinationPath dist\$zipName

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
